# Generated by Django 4.1.3 on 2022-11-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_comment_like_women_delete_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
    ]
