# Generated by Django 4.1.3 on 2022-11-17 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_remove_category_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_now', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('author_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ragu', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ragu', to='posts.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author_1',
            field=models.ManyToManyField(related_name='load', through='posts.Otvet', to=settings.AUTH_USER_MODEL),
        ),
    ]
